[package]
name = "git-worktree-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
skim = "0.10.4"
git2 = "0.19.0"
exitcode = "1.1.2"
colored = "2.1.0"
indexmap = "2.4.0"
clap = {version = "4.5.16", features = ["derive"]}
clap_complete = "4.5.24"